import { Category, Collection, Product, Coupon, StoreContent, Order, UserProfile } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-sleepwear',
    name: 'Sleep & Loungewear',
    slug: 'sleepwear',
    description: 'Ultra-soft organic bamboo & modal sleepwear designed for restful, dreamy nights.',
    image_url: '/images/collection-sleep.jpg',
    sort_order: 1,
  },
  {
    id: 'cat-clothing',
    name: 'Everyday Clothing',
    slug: 'clothing',
    description: 'Gentle, breathable organic cotton rompers, sets, and knitwear for little explorers.',
    image_url: '/images/collection-adventures.jpg',
    sort_order: 2,
  },
  {
    id: 'cat-toys',
    name: 'Toys & Imagination',
    slug: 'toys',
    description: 'Handcrafted wooden toys, heirloom plush treasures, and sensory play essentials.',
    image_url: '/images/collection-play.jpg',
    sort_order: 3,
  },
  {
    id: 'cat-nursery',
    name: 'Nursery & Bedding',
    slug: 'nursery',
    description: 'Cashmere-soft knitted blankets, starry nightlights, and soothing nursery decor.',
    image_url: '/images/moon-blanket-1.jpg',
    sort_order: 4,
  },
  {
    id: 'cat-gifts',
    name: 'Gifts & Keepsakes',
    slug: 'gifts',
    description: 'Lovingly curated gift hampers and milestone keepsakes for newborns and birthdays.',
    image_url: '/images/collection-gifts.jpg',
    sort_order: 5,
  },
  {
    id: 'cat-accessories',
    name: 'Accessories & Bags',
    slug: 'accessories',
    description: 'Little explorer canvas backpacks, shearling booties, and bonnet accessories.',
    image_url: '/images/backpack-1.jpg',
    sort_order: 6,
  },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-sleep',
    name: 'Dreamy Sleep',
    slug: 'dreamy-sleep',
    description: 'Soothing modal sleepwear, star-stitched blankets, and twilight night accessories.',
    image_url: '/images/collection-sleep.jpg',
    featured: true,
  },
  {
    id: 'col-adventures',
    name: 'Little Adventures',
    slug: 'little-adventures',
    description: 'Durable, soft layers and miniature backpacks for playground discoveries and sunny walks.',
    image_url: '/images/collection-adventures.jpg',
    featured: true,
  },
  {
    id: 'col-play',
    name: 'Play & Imagine',
    slug: 'play-and-imagine',
    description: 'Open-ended wooden toys and heirloom plush friends that spark lifelong creativity.',
    image_url: '/images/collection-play.jpg',
    featured: true,
  },
  {
    id: 'col-gifts',
    name: 'Gifts for Little Ones',
    slug: 'gifts-for-little-ones',
    description: 'Curated keepsake hampers packaged in luxury textured linen boxes with lavender ribbons.',
    image_url: '/images/collection-gifts.jpg',
    featured: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-pajamas',
    name: 'Cloudy Dreams Organic Pajama Set',
    slug: 'cloudy-dreams-organic-pajama-set',
    sku: 'LDC-PJ-001',
    category_id: 'cat-sleepwear',
    category_name: 'Sleep & Loungewear',
    base_price: 3450,
    compare_at_price: 3950,
    short_description: 'Silky breathable modal 2-piece set featuring delicate gold embroidered stars.',
    description: 'Crafted from 100% GOTS-certified organic modal fabric, our signature Cloudy Dreams Pajama Set is as soft as a twilight cloud. Features subtle gold-thread embroidered constellation stars, tagless necklines for sensitive skin, and gentle foldover cuffs on smaller sizes. Hypoallergenic and temperature-regulating for unbroken bedtime slumber.',
    status: 'active',
    featured: true,
    rating: 4.95,
    review_count: 38,
    materials: '95% Organic Modal, 5% Elastane. OEKO-TEX® Standard 100 certified.',
    care_instructions: 'Machine wash cold on gentle cycle with mild detergent. Tumble dry low or lay flat to dry in shade.',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
    collection_ids: ['col-sleep'],
    images: [
      {
        id: 'img-pj-1',
        product_id: 'prod-pajamas',
        image_url: '/images/pajama-set-1.jpg',
        alt_text: 'Cloudy Dreams Organic Pajama Set in Soft Lavender',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-pj-2',
        product_id: 'prod-pajamas',
        image_url: '/images/hero-lifestyle.jpg',
        alt_text: 'Toddler playing in Cloudy Dreams Pajama Set',
        sort_order: 2,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: 'var-pj-lav-03m',
        product_id: 'prod-pajamas',
        sku: 'LDC-PJ-LAV-03M',
        size: '0-3M',
        color: 'Soft Lavender',
        color_hex: '#8F78A8',
        price: 3450,
        stock_quantity: 14,
        low_stock_threshold: 4,
      },
      {
        id: 'var-pj-lav-36m',
        product_id: 'prod-pajamas',
        sku: 'LDC-PJ-LAV-36M',
        size: '3-6M',
        color: 'Soft Lavender',
        color_hex: '#8F78A8',
        price: 3450,
        stock_quantity: 18,
        low_stock_threshold: 4,
      },
      {
        id: 'var-pj-lav-612m',
        product_id: 'prod-pajamas',
        sku: 'LDC-PJ-LAV-612M',
        size: '6-12M',
        color: 'Soft Lavender',
        color_hex: '#8F78A8',
        price: 3450,
        stock_quantity: 22,
        low_stock_threshold: 5,
      },
      {
        id: 'var-pj-lav-12y',
        product_id: 'prod-pajamas',
        sku: 'LDC-PJ-LAV-12Y',
        size: '1-2Y',
        color: 'Soft Lavender',
        color_hex: '#8F78A8',
        price: 3650,
        stock_quantity: 9,
        low_stock_threshold: 3,
      },
      {
        id: 'var-pj-lav-23y',
        product_id: 'prod-pajamas',
        sku: 'LDC-PJ-LAV-23Y',
        size: '2-3Y',
        color: 'Soft Lavender',
        color_hex: '#8F78A8',
        price: 3650,
        stock_quantity: 12,
        low_stock_threshold: 3,
      },
      {
        id: 'var-pj-crm-612m',
        product_id: 'prod-pajamas',
        sku: 'LDC-PJ-CRM-612M',
        size: '6-12M',
        color: 'Warm Cream',
        color_hex: '#F5F0E8',
        price: 3450,
        stock_quantity: 15,
        low_stock_threshold: 4,
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        product_id: 'prod-pajamas',
        reviewer_name: 'Charlotte M.',
        rating: 5,
        title: 'Unbelievably soft & beautifully made',
        body: 'The quality of the fabric is heavenly. My 18-month old sleeps so peacefully in these. The gold star embroidery is delicate and does not scratch at all.',
        approved: true,
        verified_purchase: true,
        created_at: '2026-08-14T09:20:00Z',
      },
      {
        id: 'rev-2',
        product_id: 'prod-pajamas',
        reviewer_name: 'Elena S.',
        rating: 5,
        title: 'Worth every penny',
        body: 'We bought two sets and they have held up remarkably well after dozens of washes. Will definitely buy as baby shower gifts.',
        approved: true,
        verified_purchase: true,
        created_at: '2026-08-18T14:45:00Z',
      },
    ],
  },
  {
    id: 'prod-blanket',
    name: 'Little Moon Cashmere Knit Blanket',
    slug: 'little-moon-cashmere-knit-blanket',
    sku: 'LDC-BK-002',
    category_id: 'cat-nursery',
    category_name: 'Nursery & Bedding',
    base_price: 6800,
    compare_at_price: 7900,
    short_description: 'Heirloom ribbed cashmere & organic cotton baby blanket with embroidered crescent moon.',
    description: 'An heirloom keepsake designed to be cherished for generations. Spun from ultra-fine organic Mongolian cashmere and combed long-staple cotton, this blanket features a hand-stitched crescent moon motif with micro-scalloped lavender piping. Perfectly sized for cribs, strollers, and cozy rocking chair bedtime stories.',
    status: 'active',
    featured: true,
    rating: 5.0,
    review_count: 26,
    materials: '30% Mongolian Cashmere, 70% Organic Combed Cotton.',
    care_instructions: 'Hand wash gently in lukewarm water with wool detergent. Dry flat on a clean towel. Do not wring.',
    created_at: '2026-08-02T11:00:00Z',
    updated_at: '2026-08-21T11:00:00Z',
    collection_ids: ['col-sleep', 'col-gifts'],
    images: [
      {
        id: 'img-bk-1',
        product_id: 'prod-blanket',
        image_url: '/images/moon-blanket-1.jpg',
        alt_text: 'Little Moon Cashmere Knit Blanket in Warm Ivory',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-bk-2',
        product_id: 'prod-blanket',
        image_url: '/images/collection-sleep.jpg',
        alt_text: 'Little Moon Blanket draped in baby nursery',
        sort_order: 2,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: 'var-bk-crm-std',
        product_id: 'prod-blanket',
        sku: 'LDC-BK-CRM-STD',
        size: 'One Size (100x80cm)',
        color: 'Ivory Cream & Lavender',
        color_hex: '#F5F0E8',
        price: 6800,
        stock_quantity: 24,
        low_stock_threshold: 5,
      },
      {
        id: 'var-bk-lav-std',
        product_id: 'prod-blanket',
        sku: 'LDC-BK-LAV-STD',
        size: 'One Size (100x80cm)',
        color: 'Soft Lavender',
        color_hex: '#BEB2D4',
        price: 6800,
        stock_quantity: 16,
        low_stock_threshold: 4,
      },
    ],
    reviews: [
      {
        id: 'rev-3',
        product_id: 'prod-blanket',
        reviewer_name: 'Sophia T.',
        rating: 5,
        title: 'The ultimate baby gift',
        body: 'Received this in our gift registry and it is hands down the most beautiful baby blanket we own. Incredibly soft and weighted just right.',
        approved: true,
        verified_purchase: true,
        created_at: '2026-08-19T11:15:00Z',
      },
    ],
  },
  {
    id: 'prod-romper',
    name: 'Lavender Star Ribbed Romper',
    slug: 'lavender-star-ribbed-romper',
    sku: 'LDC-RP-003',
    category_id: 'cat-clothing',
    category_name: 'Everyday Clothing',
    base_price: 2650,
    compare_at_price: 3100,
    short_description: 'Cozy waffle-ribbed organic romper with coconut shell buttons and easy diaper snaps.',
    description: 'Designed for effortless daily dressing and cozy lounging. Our Lavender Star Romper features fine rib-knit organic cotton, sustainable coconut shell buttons down the placket, and concealed nickel-free snap closures along the inner leg for quick changes. Stretches gently with your baby’s movements.',
    status: 'active',
    featured: true,
    rating: 4.88,
    review_count: 42,
    materials: '96% Organic Ribbed Cotton, 4% Spandex for gentle elasticity.',
    care_instructions: 'Machine wash warm with like colors. Tumble dry medium. Warm iron if needed.',
    created_at: '2026-08-03T12:00:00Z',
    updated_at: '2026-08-22T12:00:00Z',
    collection_ids: ['col-adventures'],
    images: [
      {
        id: 'img-rp-1',
        product_id: 'prod-romper',
        image_url: '/images/star-romper-1.jpg',
        alt_text: 'Lavender Star Ribbed Romper flat lay with coconut buttons',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-rp-2',
        product_id: 'prod-romper',
        image_url: '/images/story-editorial.jpg',
        alt_text: 'Baby wearing Lavender Star Ribbed Romper',
        sort_order: 2,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: 'var-rp-lav-03m',
        product_id: 'prod-romper',
        sku: 'LDC-RP-LAV-03M',
        size: '0-3M',
        color: 'Lavender Stripe',
        color_hex: '#8F78A8',
        price: 2650,
        stock_quantity: 12,
        low_stock_threshold: 3,
      },
      {
        id: 'var-rp-lav-36m',
        product_id: 'prod-romper',
        sku: 'LDC-RP-LAV-36M',
        size: '3-6M',
        color: 'Lavender Stripe',
        color_hex: '#8F78A8',
        price: 2650,
        stock_quantity: 16,
        low_stock_threshold: 4,
      },
      {
        id: 'var-rp-lav-612m',
        product_id: 'prod-romper',
        sku: 'LDC-RP-LAV-612M',
        size: '6-12M',
        color: 'Lavender Stripe',
        color_hex: '#8F78A8',
        price: 2650,
        stock_quantity: 20,
        low_stock_threshold: 5,
      },
      {
        id: 'var-rp-lav-12y',
        product_id: 'prod-romper',
        sku: 'LDC-RP-LAV-12Y',
        size: '1-2Y',
        color: 'Lavender Stripe',
        color_hex: '#8F78A8',
        price: 2850,
        stock_quantity: 10,
        low_stock_threshold: 3,
      },
    ],
  },
  {
    id: 'prod-plush',
    name: 'Dream Bunny Heirloom Organic Plush',
    slug: 'dream-bunny-heirloom-organic-plush',
    sku: 'LDC-TY-004',
    category_id: 'cat-toys',
    category_name: 'Toys & Imagination',
    base_price: 2450,
    compare_at_price: 2900,
    short_description: 'Handcrafted organic linen plush bunny with floral ruffle collar and embroidered eyes.',
    description: 'Meet the Dream Bunny—a comforting bedtime companion crafted from washed natural Belgian linen and stuffed with hypoallergenic recycled corn fiber. Safe for newborns from birth, featuring hand-embroidered facial features and charming lavender floral ear linings.',
    status: 'active',
    featured: true,
    rating: 5.0,
    review_count: 54,
    materials: '100% Belgian Washed Linen shell, 100% Hypoallergenic corn fiber fill.',
    care_instructions: 'Spot clean with warm water or hand wash gently in laundry bag. Air dry completely.',
    created_at: '2026-08-04T14:00:00Z',
    updated_at: '2026-08-22T14:00:00Z',
    collection_ids: ['col-play', 'col-gifts'],
    images: [
      {
        id: 'img-pl-1',
        product_id: 'prod-plush',
        image_url: '/images/bunny-plush-1.jpg',
        alt_text: 'Dream Bunny Heirloom Organic Plush Toy',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-pl-2',
        product_id: 'prod-plush',
        image_url: '/images/collection-play.jpg',
        alt_text: 'Dream Bunny in children playroom',
        sort_order: 2,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: 'var-pl-crm-std',
        product_id: 'prod-plush',
        sku: 'LDC-TY-PL-CRM',
        size: 'Medium (32cm)',
        color: 'Natural Cream & Lavender',
        color_hex: '#F5F0E8',
        price: 2450,
        stock_quantity: 28,
        low_stock_threshold: 6,
      },
    ],
  },
  {
    id: 'prod-backpack',
    name: 'Tiny Explorer Mini Canvas Backpack',
    slug: 'tiny-explorer-mini-canvas-backpack',
    sku: 'LDC-BP-005',
    category_id: 'cat-accessories',
    category_name: 'Accessories & Bags',
    base_price: 2850,
    compare_at_price: 3400,
    short_description: 'Vintage-inspired children canvas backpack with vegan leather straps and brass hardware.',
    description: 'The sweetest pack for nursery, picnics, and weekend adventures. Built with water-resistant heavy organic cotton canvas, easy magnetic snap clasps under genuine leather accents, padded breathable shoulder straps, and an inner waterproof pocket for water bottles and snack boxes.',
    status: 'active',
    featured: true,
    rating: 4.92,
    review_count: 19,
    materials: 'Water-repellent 16oz Organic Cotton Canvas, Vegan Leather Trim, Solid Brass Hardware.',
    care_instructions: 'Wipe clean with a damp sponge and gentle soap. Do not submerge or machine wash.',
    created_at: '2026-08-05T09:00:00Z',
    updated_at: '2026-08-23T09:00:00Z',
    collection_ids: ['col-adventures'],
    images: [
      {
        id: 'img-bp-1',
        product_id: 'prod-backpack',
        image_url: '/images/backpack-1.jpg',
        alt_text: 'Tiny Explorer Mini Canvas Backpack in Lavender & Cream',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-bp-2',
        product_id: 'prod-backpack',
        image_url: '/images/collection-adventures.jpg',
        alt_text: 'Toddler wearing Tiny Explorer Backpack outdoors',
        sort_order: 2,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: 'var-bp-lav-std',
        product_id: 'prod-backpack',
        sku: 'LDC-BP-LAV-STD',
        size: 'One Size (3-6 Years)',
        color: 'Lavender & Cream',
        color_hex: '#8F78A8',
        price: 2850,
        stock_quantity: 15,
        low_stock_threshold: 4,
      },
      {
        id: 'var-bp-crm-std',
        product_id: 'prod-backpack',
        sku: 'LDC-BP-CRM-STD',
        size: 'One Size (3-6 Years)',
        color: 'Warm Cream & Tan',
        color_hex: '#EBE3D7',
        price: 2850,
        stock_quantity: 11,
        low_stock_threshold: 3,
      },
    ],
  },
  {
    id: 'prod-gift-hamper',
    name: 'Little Welcome Heirloom Gift Hamper',
    slug: 'little-welcome-heirloom-gift-hamper',
    sku: 'LDC-GH-006',
    category_id: 'cat-gifts',
    category_name: 'Gifts & Keepsakes',
    base_price: 8500,
    compare_at_price: 9800,
    short_description: 'Curated luxury newborn gift set in embossed linen keepsake box with hand-tied silk ribbon.',
    description: 'The definitive luxury welcome gift for new arrivals. Includes our Little Moon Cashmere Baby Blanket, hand-knitted merino wool booties, wooden star teething rattle, organic cotton swaddle, and an embossed golden foil greeting card ready with your custom heartfelt message.',
    status: 'active',
    featured: true,
    rating: 5.0,
    review_count: 31,
    materials: 'Gift box made from recycled linen-covered bookcloth. Products 100% certified organic.',
    care_instructions: 'Individual product care labels enclosed within keepsake box.',
    created_at: '2026-08-06T15:00:00Z',
    updated_at: '2026-08-23T15:00:00Z',
    collection_ids: ['col-gifts', 'col-sleep'],
    images: [
      {
        id: 'img-gh-1',
        product_id: 'prod-gift-hamper',
        image_url: '/images/collection-gifts.jpg',
        alt_text: 'Little Welcome Heirloom Gift Hamper in linen box',
        sort_order: 1,
        is_primary: true,
      },
      {
        id: 'img-gh-2',
        product_id: 'prod-gift-hamper',
        image_url: '/images/moon-blanket-1.jpg',
        alt_text: 'Blanket and booties inside gift hamper',
        sort_order: 2,
        is_primary: false,
      },
    ],
    variants: [
      {
        id: 'var-gh-03m-lav',
        product_id: 'prod-gift-hamper',
        sku: 'LDC-GH-LAV-03M',
        size: 'Newborn (0-3M)',
        color: 'Lavender & Cream Silk',
        color_hex: '#8F78A8',
        price: 8500,
        stock_quantity: 8,
        low_stock_threshold: 2,
      },
      {
        id: 'var-gh-36m-crm',
        product_id: 'prod-gift-hamper',
        sku: 'LDC-GH-CRM-36M',
        size: 'Baby (3-6M)',
        color: 'Warm Ivory & Gold',
        color_hex: '#F5F0E8',
        price: 8500,
        stock_quantity: 6,
        low_stock_threshold: 2,
      },
    ],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-dream10',
    code: 'DREAM10',
    discount_type: 'percentage',
    discount_value: 10,
    minimum_order: 3000,
    starts_at: '2026-01-01T00:00:00Z',
    usage_count: 142,
    active: true,
  },
  {
    id: 'coup-welcome20',
    code: 'WELCOME20',
    discount_type: 'percentage',
    discount_value: 20,
    minimum_order: 5000,
    starts_at: '2026-01-01T00:00:00Z',
    usage_count: 89,
    active: true,
  },
  {
    id: 'coup-littlestar',
    code: 'LITTLESTAR',
    discount_type: 'fixed',
    discount_value: 500,
    minimum_order: 4000,
    starts_at: '2026-01-01T00:00:00Z',
    usage_count: 45,
    active: true,
  },
];

export const INITIAL_STORE_CONTENT: StoreContent = {
  announcement_bar: {
    enabled: true,
    text: 'Free express delivery across Nepal on orders over Rs. 4,000 | Complimentary gift wrapping',
    link_text: 'Shop New Arrivals',
    link_url: '/shop',
    free_shipping_threshold: 4000,
  },
  hero_section: {
    badge: 'New Collection',
    headline: 'Where Little\nThings Become\nBig Dreams',
    subheadline: 'Thoughtfully made clothes and toys for every little adventure.',
    primary_cta_text: 'New Collection',
    primary_cta_link: '/shop?sort=newest',
    secondary_cta_text: 'Explore Collection',
    secondary_cta_link: '/shop',
    image_url: '/images/hero-lifestyle.jpg',
  },
  promo_editorial: {
    badge: 'CURATED HEIRLOOM GIFTS',
    headline: 'A Little Magic for Every Moment',
    subheadline: 'From organic sleep sets to handcrafted wooden treasures, discover thoughtful keepsakes made to be loved forever.',
    cta_text: 'Shop Curated Gifts',
    cta_link: '/collections/gifts-for-little-ones',
    image_url: '/images/promo-magic.jpg',
  },
  social_items: [
    {
      id: 'soc-1',
      image_url: '/images/hero-lifestyle.jpg',
      caption: 'Morning nursery sun & organic modal bedtime favorites ✨ #LittleDreamersClub',
      link: 'https://instagram.com',
      handle: '@littledreamersclub',
    },
    {
      id: 'soc-2',
      image_url: '/images/collection-adventures.jpg',
      caption: 'Little adventures in sunny fields with our mini canvas backpack 🌿',
      link: 'https://instagram.com',
      handle: '@littledreamersclub',
    },
    {
      id: 'soc-3',
      image_url: '/images/collection-sleep.jpg',
      caption: 'The sweetest dreams in cashmere-knit softness 🌙',
      link: 'https://instagram.com',
      handle: '@littledreamersclub',
    },
    {
      id: 'soc-4',
      image_url: '/images/collection-play.jpg',
      caption: 'Imaginative mornings with handcrafted wooden treasures & Dream Bunny 🧸',
      link: 'https://instagram.com',
      handle: '@littledreamersclub',
    },
  ],
  store_settings: {
    store_name: 'Little Dreamers Club',
    support_email: 'care@littledreamersclub.com',
    support_phone: '+977 9801234567',
    currency: 'NPR',
    currency_symbol: 'Rs.',
    standard_shipping_fee: 150,
    express_shipping_fee: 300,
    free_shipping_threshold: 4000,
    tax_rate: 0,
  },
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    order_number: 'LDC-2026-001289',
    user_id: 'user-demo-1',
    guest_email: 'emily.watson@example.com',
    guest_phone: '+977 9841234567',
    status: 'Delivered',
    payment_status: 'Paid',
    payment_method: 'online',
    subtotal: 6900,
    discount: 690,
    shipping: 0,
    tax: 0,
    total: 6210,
    coupon_code: 'DREAM10',
    shipping_address: {
      fullName: 'Aarya Sharma',
      email: 'aarya.sharma@example.com',
      phone: '+977 9841234567',
      addressLine1: 'Baluwatar, Ward 4',
      addressLine2: 'Near Russian Embassy',
      city: 'Kathmandu',
      provinceState: 'Bagmati Province',
      postalCode: '44600',
      country: 'Nepal',
      deliveryNotes: 'Please ring bell at main gate.',
    },
    items: [
      {
        id: 'item-101',
        product_variant_id: 'var-pj-lav-612m',
        product_name: 'Cloudy Dreams Organic Pajama Set',
        variant_details: 'Size: 6-12M, Color: Soft Lavender',
        unit_price: 3450,
        quantity: 2,
        total: 6900,
        image_url: '/images/pajama-set-1.jpg',
      },
    ],
    tracking_number: 'NPL-EXP-99281',
    carrier: 'Nepal Express Courier',
    created_at: '2026-08-16T14:30:00Z',
    updated_at: '2026-08-18T16:00:00Z',
  },
  {
    id: 'ord-102',
    order_number: 'LDC-2026-001392',
    user_id: 'user-demo-1',
    guest_email: 'emily.watson@example.com',
    guest_phone: '+977 9841234567',
    status: 'Shipped',
    payment_status: 'Paid',
    payment_method: 'wallet',
    subtotal: 6800,
    discount: 0,
    shipping: 0,
    tax: 0,
    total: 6800,
    shipping_address: {
      fullName: 'Aarya Sharma',
      email: 'aarya.sharma@example.com',
      phone: '+977 9841234567',
      addressLine1: 'Baluwatar, Ward 4',
      city: 'Kathmandu',
      provinceState: 'Bagmati Province',
      postalCode: '44600',
      country: 'Nepal',
    },
    items: [
      {
        id: 'item-102',
        product_variant_id: 'var-bk-crm-std',
        product_name: 'Little Moon Cashmere Knit Blanket',
        variant_details: 'Size: One Size (100x80cm), Color: Ivory Cream & Lavender',
        unit_price: 6800,
        quantity: 1,
        total: 6800,
        image_url: '/images/moon-blanket-1.jpg',
      },
    ],
    tracking_number: 'KTM-PRI-88192',
    carrier: 'Sundar Express Delivery',
    created_at: '2026-08-22T08:15:00Z',
    updated_at: '2026-08-23T10:00:00Z',
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'profile-demo-1',
  user_id: 'user-demo-1',
  full_name: 'Aarya Sharma',
  email: 'aarya.sharma@example.com',
  phone: '+977 9841234567',
  role: 'customer',
  default_shipping_address: {
    fullName: 'Aarya Sharma',
    email: 'aarya.sharma@example.com',
    phone: '+977 9841234567',
    addressLine1: 'Baluwatar, Ward 4',
    addressLine2: 'Near Russian Embassy',
    city: 'Kathmandu',
    provinceState: 'Bagmati Province',
    postalCode: '44600',
    country: 'Nepal',
  },
  created_at: '2026-08-01T00:00:00Z',
  updated_at: '2026-08-20T00:00:00Z',
};

export const DEMO_USER_PROFILE = INITIAL_USER_PROFILE;
